// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { ThreadProjectEnvState } from "./ThreadProjectEnvState";

export type ThreadProjectEnvStatus = { threadId: string, status: ThreadProjectEnvState, cwd: AbsolutePathBuf | null, envrcPath: AbsolutePathBuf | null, message: string | null, updatedAt: bigint, watchedInputCount: number, };
